### ISSUE TITLE
bar color

### ISSUE THREAD

**Issue by KingRyuShin** [mythicrp/mythic_progbar#2]
How to get the bar color like in the screenshot ? I've just downloaded the script and the bar is red only and a big rectangle.

**Comment by Alzar** [comment]
This is being maintained as the actual resource I am personally using so theming goes off what I am using. Which has changed since I first created it.

If you're wanting the old style back, go view the css from a [prior commit](https://github.com/mythicrp/mythic_progbar/blob/9207fb5c8cd23a2c7432c77389e32817b7903afe/html/css/style.css) and use that
